### ISSUE TITLE
[BUG: Internal] Blank lines cause huge gap

### ISSUE THREAD

**Issue by nousernameavailableanymore** [tnichols217/obsidian-columns#25]
This is follow up to issue #20 .

After the update, the situation is now reversed.
Instead of having blank lines causing a large gap when Obsidian Columns is placed inside Admonitions, it now shows a large gap just using Obsidian Columns (without anything else).

Test Code ("Without Admonition"):
`````
````col
```col-md
line1

line2
```
```col-md
line1

line2
```
````
`````

Result:
![image](https://user-images.githubusercontent.com/45376324/173971574-d21212db-e9a8-432e-8dac-2d84d70f35e5.png)

**Comment by nousernameavailableanymore** [comment]
A workaround seems to be this:
```
.cm-preview-code-block .columnParent p {
    margin-bottom: -1em !important;
}
```


Not sure if this is an actual "fix" as I dont know what actually caused the issue in the first place or if the workaround has any other impact.

**Comment by tnichols217** [comment]
Fixed in commit [d065bf3](https://github.com/tnichols217/obsidian-columns/commit/d065bf32e89c2f09bcce94e8c80b67ff1e7b70ee) version [1.1.8](https://github.com/tnichols217/obsidian-columns/releases/tag/1.1.8)

By using 
```css
.columnParent {
    white-space: normal;
}

.cm-preview-code-block .admonition-content .columnParent p {
    white-space: pre-wrap;
}
```
snippet
