### ISSUE TITLE
[BUG: Internal] Rendering of bullet points broken when only using "col"

### ISSUE THREAD

**Issue by nousernameavailableanymore** [tnichols217/obsidian-columns#26]
# Only using "col" for normal text
Test code:
````
```col
Line1
Line2
Line3

Line4
Line5
```````

Result:
![image](https://user-images.githubusercontent.com/45376324/173972136-15528ecf-952d-4d16-8826-3ccbd384d838.png)

# Only using "col" with bullet points
Test Code:
````
```col
- Line1
- Line2
- Line3

- Line4
- Line5
```
````

Result:
![image](https://user-images.githubusercontent.com/45376324/173972245-aa7468ad-d01f-4e6a-866d-b33ac8fe7d9a.png)

By the way: this looked a bit better in 1.1.6 but not by much. The bullet points and the text were at least aligned but the gap was still too large and no column break was added.

**Comment by tnichols217** [comment]
Fixed in commit [d065bf3](https://github.com/tnichols217/obsidian-columns/commit/d065bf32e89c2f09bcce94e8c80b67ff1e7b70ee) version [1.1.8](https://github.com/tnichols217/obsidian-columns/releases/tag/1.1.8)

By using 
```css
.columnParent {
    white-space: normal;
}

.cm-preview-code-block .admonition-content .columnParent p {
    white-space: pre-wrap;
}
```
snippet
